[project]
name = "qsim-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "andromeda7063", email = "abhinavsriram7063@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "libqsim",
    "matplotlib>=3.11.2",
    "pyside6>=6.11.2",
]

[project.scripts]
qsim-gui = "qsim_gui:main"

[build-system]
requires = ["uv_build>=0.9.15,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
libqsim = { workspace = true }
